name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      # https://github.com/gradle/gradle-build-action
      - name: ⚙️ Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 3.1
          arguments: build

      # https://github.com/actions/upload-artifact
      - name: 📚 Publish test results
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Test results
          path: |
            org.eclipse.virgo.bundlor/build/reports/tests/test/
            org.eclipse.virgo.bundlor.ant/build/reports/tests/test/
            org.eclipse.virgo.bundlor.blint/build/reports/tests/test/
            org.eclipse.virgo.bundlor.commandline/build/reports/tests/test/
            org.eclipse.virgo.bundlor.diff/build/reports/tests/test/
            org.eclipse.virgo.bundlor.gradle/build/reports/tests/test/
            org.eclipse.virgo.bundlor.maven/build/reports/tests/test/
